# Change these first
owner: investor-central-club # Your GitHub organization or username, where this repository lives
repo: icc-status # The name of this repository

sites:
  - name: investorcentralclub
    url: https://www.investorcentralclub.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://investorcentralclub.com/static/IC-logo-mini.png
  name: Investor Central Club
  introTitle: "**InvestorCentralClub** is a community of thousands of traders & investors that want to see you succeed."
  introMessage: InvestorCentralClub status page **real-time** data from our [InvestorCentralClub.com](https://investorcentralclub.com).)
  navbar:
    - title: Status
      href: /
    - title: InvestorCentralClub
      href: https://investorcentralclub.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
